[package]
name = "commit_log"
version = "0.1.0"
authors = ["Marcelo Boeira <me@marceloboeira.com>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
log = "0.4"
derive_more = "0.99"

[dev-dependencies]
tempfile = "3"
