language: rust

cache: cargo

os:
  - linux
  - osx

rust:
  - nightly

script:
  # Make sure build pass
  - cargo build --verbose --all

  # Run binary tests
  - cargo test --verbose --all

  # Run commit_log sub-crate tests
  - cd commit_log/
  - cargo test --tests

  # Run custom benchmark
  - cd ../
  - cargo run --release --bin voik_benchmark
