[package]
name = "voik"
version = "0.1.0"
authors = ["Marcelo Boeira <me@marceloboeira.com>"]

[dependencies]
dirs = "1.0.5"

[dependencies.commit_log]
path = "commit_log"

[[bin]]
name = "voik"
path = "src/voik.rs"

[[bin]]
name = "voik_benchmark"
path = "src/benchmark.rs"
