version: "3.7"

services:
  test_watcher:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.test
    command: ["funzzy"]
    working_dir: "/voik"
    volumes:
      - ../:/voik
    tty: true
    environment:
        - TERM=xterm-256color
